### ISSUE TITLE
[bug] Failed to Fetch Data invalid signature.

### ISSUE THREAD

**Issue by zgomez301** [siderolabs/omni-feedback#46]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Around 80% of the time one any page in dev and stg omni

Failed to Fetch Data
invalid signature.

Eventually able to see then fails to fetch again

### Expected Behavior

Does not fail to fetch data

### Steps To Reproduce

1. log into omni 
2. click anywhere

### What browsers are you seeing the problem on?

Firefox, Chrome

### Anything else?

Was in a video call throughout the process with no drops.

**Comment by zgomez301** [comment]
![image](https://github.com/siderolabs/omni-feedback/assets/70731147/5cff14c4-d2f9-483e-b9a5-7e810d8c2730)

**Comment by smira** [comment]
I can only see successful attempts to use this instance from this user, two logins within a couple of minutes recently.

**Comment by smira** [comment]
Scratch that, I see the errors

**Comment by TimJones** [comment]
This should be fixed in `v0.10.1`.

**Comment by zgomez301** [comment]
Still happening in v0.10.1
Although its 90% less frequent and I can have some functionality
![image](https://github.com/siderolabs/omni-feedback/assets/70731147/de942fc7-d01f-4e8e-8b3e-868bbde8e4cf)

**Comment by Unix4ever** [comment]
If you log out from Omni does it still show `Ongoing Tasks` in the top right corner?
This screen:
![image](https://github.com/siderolabs/omni-feedback/assets/830532/0aa5d4b5-1938-4cd1-851e-8f01698eb5c3)

If yes, then cleaning up browser cache might help.

**Comment by zgomez301** [comment]
Nope 
![image](https://github.com/siderolabs/omni-feedback/assets/70731147/4d8052dc-d7ec-49dd-a83d-b91f8aac3e1a)

**Comment by Unix4ever** [comment]
Hmm, ok. Would be nice if you can find the failed request in the `Network` tab to see which watch fails.
![image](https://github.com/siderolabs/omni-feedback/assets/830532/8e5dc967-efc6-4561-8c15-e7c1c134e969)

And maybe cleaning up cache will still help.

**Comment by zgomez301** [comment]
Failed request:
![image](https://github.com/siderolabs/omni-feedback/assets/70731147/e70acf5f-34d3-41e6-b893-2220dee0b94e)
Response {error: {code: 16, message: "invalid signature"}}

Compared to successful one the failed request headers are missing 
![image](https://github.com/siderolabs/omni-feedback/assets/70731147/6962207d-010c-4dc4-a940-f7c5ab88cf4a)

Grpc-Metadata-Content-Type: application/grpc
